#########################################
#Oh-My-Zsh configuration
#########################################

#Paths

export ZSH=$HOME/.oh-my-zsh
ZSH_CUSTOM=$HOME/.zsh_custom

#General Settings

HYPHEN_INSENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
#export UPDATE_ZSH_DAYS=13
#DISABLE_AUTO_TITLE="true"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

#Theme

ZSH_THEME="powerlevel9k/powerlevel9k"

#Plugin List

plugins=(git wd urltools python lol zsh-syntax-highlighting)

#Oh-My-Zsh initialization

source $ZSH/oh-my-zsh.sh

##########################################
#General configuration
#########################################

# Locale
export LANG=en_US.UTF-8

#Xorg autostart



##########################################
#Zsh-Syntax-highlighting configuration
#########################################

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets cursor)

##########################################
#Powerlevel9k configuration
#########################################

#General Settings

POWERLEVEL9K_PROMPT_ON_NEWLINE=true 
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3 
POWERLEVEL9K_SHORTEN_DELIMITER=".." 
POWERLEVEL9K_SHORTEN_STRATEGY="Default"
POWERLEVEL9K_MODE='compatible'

#Contents

POWERLEVEL9K_CUSTOM_CONTEXT="echo $(whoami)@$(hostname)"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(ssh custom_context dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time)

#Icons

POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='>' 
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='<'
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='>'
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='<'

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=' > '

#POWERLEVEL9K_HOME_ICON=''
#POWERLEVEL9K_HOME_SUB_ICON=''
#POWERLEVEL9K_FOLDER_ICON=''

#Colors

EMPTY='empty'

POWERLEVEL9K_TIME_FOREGROUND=magenta
POWERLEVEL9K_TIME_BACKGROUND=$EMPTY

POWERLEVEL9K_STATUS_OK_FOREGROUND=green
POWERLEVEL9K_STATUS_OK_BACKGROUND=$EMPTY
POWERLEVEL9K_STATUS_ERROR_FOREGROUND=red
POWERLEVEL9K_STATUS_ERROR_BACKGROUND=$EMPTY

POWERLEVEL9K_DIR_HOME_FOREGROUND=magenta
POWERLEVEL9K_DIR_HOME_BACKGROUND=$EMPTY
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND=cyan
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND=$EMPTY
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND=blue
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND=$EMPTY

POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND=cyan
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND=$EMPTY

POWERLEVEL9K_VCS_CLEAN_FOREGROUND=white
POWERLEVEL9K_VCS_CLEAN_BACKGROUND=$EMPTY
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=cyan
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=$EMPTY 
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=green
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=$EMPTY

POWERLEVEL9K_CUSTOM_CONTEXT_FOREGROUND=red
POWERLEVEL9K_CUSTOM_CONTEXT_BACKGROUND=$EMPTY
